/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellCamerasRouteImport } from './routes/_shell.cameras'
import { Route as ShellBevRouteImport } from './routes/_shell.bev'

const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellCamerasRoute = ShellCamerasRouteImport.update({
  id: '/cameras',
  path: '/cameras',
  getParentRoute: () => ShellRoute,
} as any)
const ShellBevRoute = ShellBevRouteImport.update({
  id: '/bev',
  path: '/bev',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bev': typeof ShellBevRoute
  '/cameras': typeof ShellCamerasRoute
  '/dashboard': typeof ShellDashboardRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bev': typeof ShellBevRoute
  '/cameras': typeof ShellCamerasRoute
  '/dashboard': typeof ShellDashboardRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/_shell/bev': typeof ShellBevRoute
  '/_shell/cameras': typeof ShellCamerasRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bev' | '/cameras' | '/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bev' | '/cameras' | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/_shell/bev'
    | '/_shell/cameras'
    | '/_shell/dashboard'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/cameras': {
      id: '/_shell/cameras'
      path: '/cameras'
      fullPath: '/cameras'
      preLoaderRoute: typeof ShellCamerasRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/bev': {
      id: '/_shell/bev'
      path: '/bev'
      fullPath: '/bev'
      preLoaderRoute: typeof ShellBevRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellBevRoute: typeof ShellBevRoute
  ShellCamerasRoute: typeof ShellCamerasRoute
  ShellDashboardRoute: typeof ShellDashboardRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellBevRoute: ShellBevRoute,
  ShellCamerasRoute: ShellCamerasRoute,
  ShellDashboardRoute: ShellDashboardRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
